# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ArchaeoAstroInsight
                                 A QGIS plugin
 This plugin enables users to perform archaeoastronomy studies by computing the azimuth and horizon altitude indicated by a specific bearing (line).
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-10-30
        copyright            : (C) 2021 by Marc Frincu, Stefania Ionescu
        email                : frincu.marc@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ArchaeoAstroInsight class from file ArchaeoAstroInsight.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .a2i import ArchaeoAstroInsight
    return ArchaeoAstroInsight(iface)
